### ISSUE TITLE
Examples does not compile under Xcode 11 pod 1.5.3

### ISSUE THREAD

**Issue by evgzor** [Narek1994/NSVLocalizationKit#1]
![Снимок экрана 2019-09-24 в 15 38 33](https://user-images.githubusercontent.com/5227456/65512175-62e9ad00-dee1-11e9-9eff-277b02dcf8bb.png)

**Comment by Narek1994** [comment]
Hi, could you please try one more time, there was a missing file, test view controller. I don't update my Xcode, just using latest beta version, at it is working in beta version. Please try it and if same issue raises, I will download official version and check in there.
And also please remove pod files and run pod update in example project, maybe there is a problem with pod files, Thanks.

**Comment by evgzor** [comment]
![Снимок экрана 2019-09-24 в 16 05 30](https://user-images.githubusercontent.com/5227456/65514065-333ca400-dee5-11e9-8e62-f86728c713f0.png)
checkout latest commit and run pod install. Looks problem not in pods but in example project structure.

**Comment by Narek1994** [comment]
From the paths I can see that files which are missing are in Pods directory.
check Martinpristas answer from here.
https://stackoverflow.com/questions/27109476/incorrect-path-for-pods-debug-xcconfig-in-xcode
or this one
https://forums.developer.apple.com/thread/115475
I can't reproduce it in my side, downloaded example successfully runs on my machine, but I faced that kind of problem in one of my previous projects.
Thanks.

**Comment by evgzor** [comment]
Sorry I tried from different Mac's and also my colleagues cannot complile yours examples. For sure u may leave it as it is but it does not compiles at all. Let's wait when more people start to complain.

**Comment by Narek1994** [comment]
ok, thanks for information I will try to figure out the problem, unfortunately it is not reproducing on any of our Macs, I will try to update my Mac also to check on it.

**Comment by evgzor** [comment]
pod version 1.5.3 does not allow to compile, on 1.8.0 it compiles. So just point to the minimum cocoa pods version that should be in use.

**Comment by Narek1994** [comment]
thanks for info, I will check it on that version
